version: '3.8'

services:
  db:
    image: postgres:15
    container_name: mediweb_db
    restart: always
    environment:
      POSTGRES_DB: mediweb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432" # 5432 és 5433 foglalt volt a hoston, váltás 5434-re
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev: