version: '3.8'

services:
  db:
    image: postgres:15
    container_name: mediweb_db
    restart: always
    environment:
      POSTGRES_DB: mediweb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev: