spring:
  application:
    name: MediTrack
  config:
    import: optional:dotenv:./.env,optional:dotenv:./.env.development
  devtools:
    restart.enabled: false
    livereload.enabled: false
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/meditrack}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

logging:
  level:
    root: info
    "org.springframework.web": warn
    "org.hibernate": error

# custom external API config
google:
  api:
    key: ${GOOGLE_API_KEY:}
    cx: ${GOOGLE_CX:}

server:
  servlet:
    session:
      cookie:
        secure: false
        http-only: true
        same-site: LAX

# web push config
push:
  vapid:
    public-key: ${PUSH_VAPID_PUBLIC_KEY:}
    private-key: ${PUSH_VAPID_PRIVATE_KEY:}
    subject: ${PUSH_VAPID_SUBJECT:mailto:admin@localhost}

# cors policy (custom binding class expected)
cors:
  allowed-origins:
    - http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"